# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5645cf88074f3d1bad586588320df2baa789608172c115245d9bf30b1ab47ab5f464d8f6ec0a23e787c04f23393a134ae8386d4443246924d08c5c6a8001152

test:
  secret_key_base: 403338564c76442b55cc333c8c9000384bbcee528d0b44eb261495cf6fcb9b18b076f61d9416150436efa37a5da229e7cc99b6af1954ace43b1ba93413a7cf56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
